#%RAML 1.0
title: craft-onlineshopping
description: Rest Api documentation
version: 1.0 
mediaType:
  - application/json
uses:
  lib: library.raml 
/products:
  get:
    queryParameters: 
      name: 
       type: string 
       description: the name of the product 
       maxLength: 20 
       example: Dell
      productid: 
        type: integer 
        description: the od of the product 
        required: false 
        example: 123 
      headers: 
      connection-type: 
          description: multiple connection is allowed 
          type: array 
          required: false 
      conn-track: 
            description: connection session id mandatory 
            type: integer 
            required: true 
            example: 8456783464378 
    responses:
        200:
          body: 
            application/json:
             type: lib.product[]
             example: !include examples/products.raml
  is:
    - lib.404response
  /{product}:
   get:
    responses:
      200: 
        body:
          application/json:
            type: lib.product
            example: !include examples/product.raml
    is:
      - lib.404response
/orders:
  get:
    responses:
      201:
        body:
          application/json:
            type: lib.order
            example: !include examples/orders.raml
  type:
    lib.postres:
      examplereference1:
        {
          "orderid": 34567
        }
  /{orderId}:
/users:
  get:      
  type:
    lib.postres:
      examplereference1: 
        {
          "userid": 1234
        }
  /{user}:
    get:
      responses:
        200:
          body:
           application/json:
            type: lib.user[]
            example: !include examples/user.raml
    is:
      - lib.404response
/catagory:
  get:
  /{catId}: